import { z } from "zod";

export const VehicleData = z.object({
  $list: z.array(
    z
      .object({
        id: z.number(),
      })
      .passthrough()
  ),
  $count: z.object({
    $total: z.number(),
  }),
  // .passthrough()
});

export const VehicleItem = z
  .object({
    id: z.number(),
    type: z.string(),
    isNew: z.boolean(),
    modelCode: z.string().optional(),
    title: z.string(),
    // brand: z.object({ id: z.number(), label: z.string() }),
    // series: z.object({ id: z.number(), label: z.string() }),
    // bodyType: z.object({ id: z.number(), label: z.string() }),
    // seriesCode: z.string(),
    // productionYear: z.number(),
    // mileage: z.number(),
    // fuel: z.object({ id: z.number(), label: z.string() }),
    // consumptionFuel: z.number(),
    // emission: z.number(),
    // emissionStandard: z.object({ id: z.number(), label: z.string() }),
    // powerKW: z.number(),
    // powerHP: z.number(),
    // capacity: z.number(),
    // transmission: z.object({ id: z.number(), label: z.string() }),
    // color: z.object({ code: z.string(), id: z.number(), label: z.string() }),
    // images: z.number(),
    // imagesLastChanged: z.string(),
    // exterior360: z.boolean(),
    // interior360: z.boolean(),
    // warranty: z.number(),
    // usedBrand: z.boolean(),
    // reservable: z.boolean(),
    // vatReclaimable: z.boolean(),
    // leasable: z.boolean(),
    leaseProduct: z
      .object({
        // type: z.string(),
        // label: z.string(),
        // downPaymentLimits: z.object({
        //   min: z.number(),
        //   max: z.number(),
        //   step: z.number(),
        //   default: z.number(),
        // }),
        // termLimits: z.object({
        //   min: z.number(),
        //   max: z.number(),
        //   step: z.number(),
        //   default: z.number(),
        // }),
        // totalAgeLimit: z.number(),
        // residualValueFactorLimits: z.array(z.array(z.null())),
        // residualValueStep: z.number(),
        // residualValueDefault: z.string(),
        // interestRates: z.array(z.array(z.null())),
      })
      .passthrough()
      .optional(),
    comfortLeaseProduct: z
      .object({
        // type: z.string(),
        // label: z.string(),
        // calculationMode: z.string(),
        // downPaymentLimits: z.object({
        //   min: z.number(),
        //   max: z.number(),
        //   step: z.number(),
        //   default: z.number(),
        // }),
        // termLimits: z.object({
        //   min: z.number(),
        //   max: z.number(),
        //   step: z.number(),
        //   default: z.number(),
        // }),
        // totalAgeLimit: z.number(),
        // annualMileageLimits: z.object({
        //   min: z.number(),
        //   max: z.number(),
        //   step: z.number(),
        //   default: z.number(),
        // }),
        // interestRates: z.array(z.array(z.null())),
        // tarRvMod: z.object({
        //   id: z.number(),
        //   tmdate: z.string(),
        //   accessoryLimit: z.number(),
        //   rvValue: z.number(),
        //   brvValue: z.number(),
        //   rvValueUsed: z.number(),
        //   brvValueUsed: z.number(),
        //   carSegmentId: z.string(),
        // }),
        // tarRvDev: z.object({
        //   term: z.number(),
        //   totalMileage: z.number(),
        //   rvDev: z.number(),
        //   rvDevUsed: z.number(),
        // }),
      })
      .passthrough()
      .optional(),
    // newPrice: z.number(),
    // optionsPrice: z.number(),
    // accessoriesPrice: z.number(),
    // transactionalPrice: z.number(),
    // dealer: z.object({
    //   id: z.number(),
    //   buno: z.string(),
    //   owner: z.string(),
    //   ownerName: z.string(),
    //   name: z.string(),
    //   legalName: z.string(),
    //   street: z.string(),
    //   zip: z.string(),
    //   city: z.string(),
    //   lat: z.number(),
    //   lng: z.number(),
    // }),
    // created: z.string(),
    // age: z.number(),
    // isYUC: z.boolean(),
    // reserved: z.boolean(),
  })
  .passthrough();
// {
//   id: 25847,
//   type: 'CAR',
//   isNew: true,
//   modelCode: '31AX',
//   title: 'BMW 420d xDrive Gran Coupe',
//   brand: { id: 1, label: 'BMW' },
//   series: { id: 4, label: 'Seria 4' },
//   bodyType: { id: 2, label: 'Coupé' },
//   seriesCode: 'G26',
//   productionYear: 2021,
//   mileage: 10,
//   fuel: { id: 2, label: 'Diesel' },
//   consumptionFuel: 5.3,
//   emission: 139,
//   emissionStandard: { id: 6, label: 'EURO 6' },
//   powerKW: 140,
//   powerHP: 190,
//   capacity: 1995,
//   transmission: { id: 0, label: 'Automatyczna' },
//   color: { code: '#808080', id: 6, label: 'Szary Brooklyn M' },
//   images: 10,
//   imagesLastChanged: '2021-12-20T15:33:16+00:00',
//   exterior360: true,
//   interior360: true,
//   warranty: 0,
//   usedBrand: false,
//   reservable: false,
//   vatReclaimable: true,
//   leasable: true,
//   leaseProduct: {
//     type: 'lease',
//     label: 'LO',
//     downPaymentLimits: { min: 0, max: 0.45, step: 1000, default: 0 },
//     termLimits: { min: 24, max: 60, step: 1, default: 48 },
//     totalAgeLimit: 120,
//     residualValueFactorLimits: [
//       [Object], [Object],
//       [Object], [Object],
//       [Object], [Object],
//       [Object], [Object],
//       [Object], [Object],
//       [Object], [Object],
//       [Object], [Object],
//       [Object], [Object],
//       [Object]
//     ],
//     residualValueStep: 0.005,
//     residualValueDefault: 'max',
//     interestRates: [ [Object], [Object], [Object], [Object] ]
//   },
//   comfortLeaseProduct: {
//     type: 'comfort_lease',
//     label: 'CL',
//     calculationMode: 'brv_based',
//     downPaymentLimits: { min: 0, max: 0.35, step: 1000, default: 0.05 },
//     termLimits: { min: 24, max: 60, step: 1, default: 24 },
//     totalAgeLimit: 96,
//     annualMileageLimits: { min: 10000, max: 50000, step: 5000, default: 15000 },
//     interestRates: [ [Object], [Object], [Object], [Object] ],
//     tarRvMod: {
//       id: 77253,
//       tmdate: '21/10/11',
//       accessoryLimit: 0.3,
//       rvValue: 0.489,
//       brvValue: 0.489,
//       rvValueUsed: 0.502,
//       brvValueUsed: 0.489,
//       carSegmentId: '2'
//     },
//     tarRvDev: { term: 24, totalMileage: 15000, rvDev: 0.0967, rvDevUsed: 0.0967 }
//   },
//   newPrice: 258400,
//   optionsPrice: 33900,
//   accessoriesPrice: 0,
//   transactionalPrice: 258400,
//   dealer: {
//     id: 28,
//     buno: '34238',
//     owner: '016',
//     ownerName: 'Zdunek Auto Premium Sp. z.o.o.',
//     name: 'Zdunek Premium Sp. z o.o.',
//     legalName: 'Zdunek Premium Sp. z o.o.',
//     street: 'Mialki Szlak 59',
//     zip: '80-717',
//     city: 'Gdańsk',
//     lat: 54.3481995,
//     lng: 18.6891094
//   },
//   created: '2021-12-20T16:00:02+00:00',
//   age: 0,
//   isYUC: false,
//   reserved: false
// }
